language: java

env:
  global:
    - NODE_VERSION="12.13.1"
    - YARN_VERSION="1.21.1"

services:
  - docker

jobs:
  include:

    - stage: publish
      if: tag =~ ^status-v.+$
      env:
        - CACHE_NAME=refetch
        - IMAGE_NAME=denniske/aoe2companion-status
      before_install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - sudo apt-get update
        - sudo apt-get -y install gettext-base
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        - chmod u+x ./kubectl
        - sudo mv kubectl /usr/local/bin/
      script:
        - cd server
        - npm install
        - npm run build
        - ls -al
        - docker build -f deploy/Dockerfile -t $IMAGE_NAME:$TRAVIS_COMMIT .
        - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - docker push $IMAGE_NAME:$TRAVIS_COMMIT
        - cd deploy
        - bash ./deploy.sh
