apiVersion: apps/v1
kind: Deployment
metadata:
  name: status
  namespace: default
  labels:
    app: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status
  template:
    metadata:
      labels:
        app: status
    spec:
      containers:
        - name: status
          image: denniske/status:$COMMIT_SHA1
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - secretRef:
                name: server-secret
          env:
            - name: PORT
              value: "80"
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name